name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_TEST_SA_KEY }}'
    - name: Set up Google Cloud Platform
      uses: google-github-actions/setup-gcloud@v2
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Build and Push Docker image
      run: gcloud builds submit --tag gcr.io/locards-bonny-test/bonny-frontend
    - name: Deploy to Cloud Run
      run: gcloud run deploy --service-account='bonny-test-frontend@locards-bonny-test.iam.gserviceaccount.com' --image='gcr.io/locards-bonny-test/bonny-frontend' --region='europe-west3' bonny-frontend